<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f0d6a5f0d1d: ccl_err + 0x9d1d (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb3)
	0x7f0d6a5f3d69: ccl_err + 0xcd69 (_Z14err_terminatorv + 0x77)
	0x7f0d663c6c12: dinkum_alt + 0x1dc12 (_ZSt9terminatev + 0x12)
	0x7f0d63b370c6: stdc++.so.6 + 0xbd0c6 (__cxa_rethrow + 0x46)
	0x7f0d68f4a51f: QtCore.so.4 + 0x18a51f (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x34f)
	0x7f0d68f4ed4b: QtCore.so.4 + 0x18ed4b (_ZN16QCoreApplication4execEv + 0xbb)
	   0x407eb1: quartus + 0x7eb1 (__gxx_personality_v0 + 0x3b1)
	0x7f0d6cea41b0: ccl_msg + 0x361b0 (_Z15msg_main_threadPv + 0x10)
	0x7f0d69f9bfac: ccl_thr + 0x7fac (thr_final_wrapper + 0xc)
	0x7f0d6cea4d55: ccl_msg + 0x36d55 (_Z18msg_thread_wrapperPFPvS_ES_ + 0x5b)
	   0x416fd5: quartus + 0x16fd5 (_Z18mem_thread_wrapperPFPvS_ES_ + 0xc5)
	0x7f0d6a5f6408: ccl_err + 0xf408 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f0d69f9c38c: ccl_thr + 0x838c (thr_thread_wrapper + 0x15)
	0x7f0d6ceb6f4d: ccl_msg + 0x48f4d (_Z12msg_exe_mainiPPKcPFiiS1_E + 0x96)
	   0x407f75: quartus + 0x7f75 (__gxx_personality_v0 + 0x475)
	0x7f0d632b2830: c.so.6 + 0x20830 (__libc_start_main + 0xf0)
	   0x407d89: quartus + 0x7d89 (__gxx_personality_v0 + 0x289)
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Wed Jun 20 12:23:52 2018
</date>
<version>Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition</version>
</internal_error>